sed s'/{{ *refs\.TODO.path *}}/\/apidocs\/TODO.html/g' | \
sed s'/{{ *refs\.TODO.path *}}/\/components\/TODO.html/g' | \
sed s'/{{ *refs\.contributing.path *}}/\/contributing.html/g' | \
sed s'/{{ *refs\.accessing-filesystem-resources-extensions-fsresource.path *}}/\/documentation\/bundles\/accessing-filesystem-resources-extensions-fsresource.html/g' | \
sed s'/{{ *refs\.apache-sling-commons-thread-pool.path *}}/\/documentation\/bundles\/apache-sling-commons-thread-pool.html/g' | \
sed s'/{{ *refs\.apache-sling-eventing-and-job-handling.path *}}/\/documentation\/bundles\/apache-sling-eventing-and-job-handling.html/g' | \
sed s'/{{ *refs\.bundle-resources-extensions-bundleresource.path *}}/\/documentation\/bundles\/bundle-resources-extensions-bundleresource.html/g' | \
sed s'/{{ *refs\.caching-services.path *}}/\/documentation\/bundles\/caching-services.html/g' | \
sed s'/{{ *refs\.commons-html-utilities.path *}}/\/documentation\/bundles\/commons-html-utilities.html/g' | \
sed s'/{{ *refs\.configuration-installer-factory.path *}}/\/documentation\/bundles\/configuration-installer-factory.html/g' | \
sed s'/{{ *refs\.content-distribution.path *}}/\/documentation\/bundles\/content-distribution.html/g' | \
sed s'/{{ *refs\.content-loading-jcr-contentloader.path *}}/\/documentation\/bundles\/content-loading-jcr-contentloader.html/g' | \
sed s'/{{ *refs\.context-aware-configuration-default-implementation.path *}}/\/documentation\/bundles\/context-aware-configuration\/context-aware-configuration-default-implementation.html/g' | \
sed s'/{{ *refs\.context-aware-configuration-override.path *}}/\/documentation\/bundles\/context-aware-configuration\/context-aware-configuration-override.html/g' | \
sed s'/{{ *refs\.context-aware-configuration-spi.path *}}/\/documentation\/bundles\/context-aware-configuration\/context-aware-configuration-spi.html/g' | \
sed s'/{{ *refs\.context-aware-configuration.path *}}/\/documentation\/bundles\/context-aware-configuration\/context-aware-configuration.html/g' | \
sed s'/{{ *refs\.datasource-providers.path *}}/\/documentation\/bundles\/datasource-providers.html/g' | \
sed s'/{{ *refs\.discovery-api-and-impl.path *}}/\/documentation\/bundles\/discovery-api-and-impl.html/g' | \
sed s'/{{ *refs\.dynamic-includes.path *}}/\/documentation\/bundles\/dynamic-includes.html/g' | \
sed s'/{{ *refs\.file-installer-provider.path *}}/\/documentation\/bundles\/file-installer-provider.html/g' | \
sed s'/{{ *refs\.internationalization-support-i18n.path *}}/\/documentation\/bundles\/internationalization-support-i18n.html/g' | \
sed s'/{{ *refs\.jcr-installer-provider.path *}}/\/documentation\/bundles\/jcr-installer-provider.html/g' | \
sed s'/{{ *refs\.log-tracers.path *}}/\/documentation\/bundles\/log-tracers.html/g' | \
sed s'/{{ *refs\.managing-permissions-jackrabbit-accessmanager.path *}}/\/documentation\/bundles\/managing-permissions-jackrabbit-accessmanager.html/g' | \
sed s'/{{ *refs\.managing-users-and-groups-jackrabbit-usermanager.path *}}/\/documentation\/bundles\/managing-users-and-groups-jackrabbit-usermanager.html/g' | \
sed s'/{{ *refs\.manipulating-content-the-slingpostservlet-servlets-post.path *}}/\/documentation\/bundles\/manipulating-content-the-slingpostservlet-servlets-post.html/g' | \
sed s'/{{ *refs\.metrics.path *}}/\/documentation\/bundles\/metrics.html/g' | \
sed s'/{{ *refs\.mime-type-support-commons-mime.path *}}/\/documentation\/bundles\/mime-type-support-commons-mime.html/g' | \
sed s'/{{ *refs\.models.path *}}/\/documentation\/bundles\/models.html/g' | \
sed s'/{{ *refs\.nosql-resource-providers.path *}}/\/documentation\/bundles\/nosql-resource-providers.html/g' | \
sed s'/{{ *refs\.org-apache-sling-junit-bundles.path *}}/\/documentation\/bundles\/org-apache-sling-junit-bundles.html/g' | \
sed s'/{{ *refs\.osgi-installer.path *}}/\/documentation\/bundles\/osgi-installer.html/g' | \
sed s'/{{ *refs\.output-rewriting-pipelines-org-apache-sling-rewriter.path *}}/\/documentation\/bundles\/output-rewriting-pipelines-org-apache-sling-rewriter.html/g' | \
sed s'/{{ *refs\.rendering-content-default-get-servlets.path *}}/\/documentation\/bundles\/rendering-content-default-get-servlets.html/g' | \
sed s'/{{ *refs\.repository-initialization.path *}}/\/documentation\/bundles\/repository-initialization.html/g' | \
sed s'/{{ *refs\.request-analysis.path *}}/\/documentation\/bundles\/request-analysis.html/g' | \
sed s'/{{ *refs\.resource-access-security.path *}}/\/documentation\/bundles\/resource-access-security.html/g' | \
sed s'/{{ *refs\.resource-editor.path *}}/\/documentation\/bundles\/resource-editor.html/g' | \
sed s'/{{ *refs\.resource-merger.path *}}/\/documentation\/bundles\/resource-merger.html/g' | \
sed s'/{{ *refs\.scheduler-service-commons-scheduler.path *}}/\/documentation\/bundles\/scheduler-service-commons-scheduler.html/g' | \
sed s'/{{ *refs\.scripting-htl.path *}}/\/documentation\/bundles\/scripting\/scripting-htl.html/g' | \
sed s'/{{ *refs\.scripting-jsp.path *}}/\/documentation\/bundles\/scripting\/scripting-jsp.html/g' | \
sed s'/{{ *refs\.scripting-thymeleaf.path *}}/\/documentation\/bundles\/scripting\/scripting-thymeleaf.html/g' | \
sed s'/{{ *refs\.scripting.path *}}/\/documentation\/bundles\/scripting.html/g' | \
sed s'/{{ *refs\.servlet-helpers.path *}}/\/documentation\/bundles\/servlet-helpers.html/g' | \
sed s'/{{ *refs\.sling-health-check-tool.path *}}/\/documentation\/bundles\/sling-health-check-tool.html/g' | \
sed s'/{{ *refs\.sling-oak-restrictions.path *}}/\/documentation\/bundles\/sling-oak-restrictions.html/g' | \
sed s'/{{ *refs\.sling-pipes.path *}}/\/documentation\/bundles\/sling-pipes.html/g' | \
sed s'/{{ *refs\.sling-query.path *}}/\/documentation\/bundles\/sling-query.html/g' | \
sed s'/{{ *refs\.sling-settings-org-apache-sling-settings.path *}}/\/documentation\/bundles\/sling-settings-org-apache-sling-settings.html/g' | \
sed s'/{{ *refs\.subsystem-installer-factory.path *}}/\/documentation\/bundles\/subsystem-installer-factory.html/g' | \
sed s'/{{ *refs\.validation.path *}}/\/documentation\/bundles\/validation.html/g' | \
sed s'/{{ *refs\.web-console-extensions.path *}}/\/documentation\/bundles\/web-console-extensions.html/g' | \
sed s'/{{ *refs\.xml-support.path *}}/\/documentation\/bundles\/xml-support.html/g' | \
sed s'/{{ *refs\.bundles.path *}}/\/documentation\/bundles.html/g' | \
sed s'/{{ *refs\.configuration.path *}}/\/documentation\/configuration.html/g' | \
sed s'/{{ *refs\.client-request-logging.path *}}/\/documentation\/development\/client-request-logging.html/g' | \
sed s'/{{ *refs\.dependency-management.path *}}/\/documentation\/development\/dependency-management.html/g' | \
sed s'/{{ *refs\.embedding-sling.path *}}/\/documentation\/development\/embedding-sling.html/g' | \
sed s'/{{ *refs\.getting-and-building-sling.path *}}/\/documentation\/development\/getting-and-building-sling.html/g' | \
sed s'/{{ *refs\.hamcrest.path *}}/\/documentation\/development\/hamcrest.html/g' | \
sed s'/{{ *refs\.htl-maven-plugin.path *}}/\/documentation\/development\/htl-maven-plugin.html/g' | \
sed s'/{{ *refs\.ide-tooling-incremental-build.path *}}/\/documentation\/development\/ide-tooling\/ide-tooling-incremental-build.html/g' | \
sed s'/{{ *refs\.ide-tooling.path *}}/\/documentation\/development\/ide-tooling.html/g' | \
sed s'/{{ *refs\.issue-tracker.path *}}/\/documentation\/development\/issue-tracker.html/g' | \
sed s'/{{ *refs\.jcr-mock.path *}}/\/documentation\/development\/jcr-mock.html/g' | \
sed s'/{{ *refs\.jspc.path *}}/\/documentation\/development\/jspc.html/g' | \
sed s'/{{ *refs\.jsr-305.path *}}/\/documentation\/development\/jsr-305.html/g' | \
sed s'/{{ *refs\.logging.path *}}/\/documentation\/development\/logging.html/g' | \
sed s'/{{ *refs\.maven-archetypes.path *}}/\/documentation\/development\/maven-archetypes.html/g' | \
sed s'/{{ *refs\.maven-launchpad-plugin.path *}}/\/documentation\/development\/maven-launchpad-plugin.html/g' | \
sed s'/{{ *refs\.maven-usage.path *}}/\/documentation\/development\/maven-usage.html/g' | \
sed s'/{{ *refs\.maventipsandtricks.path *}}/\/documentation\/development\/maventipsandtricks.html/g' | \
sed s'/{{ *refs\.monitoring-requests.path *}}/\/documentation\/development\/monitoring-requests.html/g' | \
sed s'/{{ *refs\.osgi-mock.path *}}/\/documentation\/development\/osgi-mock.html/g' | \
sed s'/{{ *refs\.release-management.path *}}/\/documentation\/development\/release-management.html/g' | \
sed s'/{{ *refs\.repository-based-development.path *}}/\/documentation\/development\/repository-based-development.html/g' | \
sed s'/{{ *refs\.resourceresolver-mock.path *}}/\/documentation\/development\/resourceresolver-mock.html/g' | \
sed s'/{{ *refs\.sling-mock.path *}}/\/documentation\/development\/sling-mock.html/g' | \
sed s'/{{ *refs\.sling-testing-tools.path *}}/\/documentation\/development\/sling-testing-tools.html/g' | \
sed s'/{{ *refs\.sling.path *}}/\/documentation\/development\/sling.html/g' | \
sed s'/{{ *refs\.slingstart.path *}}/\/documentation\/development\/slingstart.html/g' | \
sed s'/{{ *refs\.version-policy.path *}}/\/documentation\/development\/version-policy.html/g' | \
sed s'/{{ *refs\.development.path *}}/\/documentation\/development.html/g' | \
sed s'/{{ *refs\.discover-sling-in-15-minutes.path *}}/\/documentation\/getting-started\/discover-sling-in-15-minutes.html/g' | \
sed s'/{{ *refs\.getting-started.path *}}/\/documentation\/getting-started.html/g' | \
sed s'/{{ *refs\.logging.path *}}/\/documentation\/legacy\/logging.html/g' | \
sed s'/{{ *refs\.pax-exam-utils.path *}}/\/documentation\/pax-exam-utils.html/g' | \
sed s'/{{ *refs\.adapters.path *}}/\/documentation\/the-sling-engine\/adapters.html/g' | \
sed s'/{{ *refs\.architecture.path *}}/\/documentation\/the-sling-engine\/architecture.html/g' | \
sed s'/{{ *refs\.authentication-actors.path *}}/\/documentation\/the-sling-engine\/authentication\/authentication-actors.html/g' | \
sed s'/{{ *refs\.form-based-authenticationhandler.path *}}/\/documentation\/the-sling-engine\/authentication\/authentication-authenticationhandler\/form-based-authenticationhandler.html/g' | \
sed s'/{{ *refs\.openid-authenticationhandler.path *}}/\/documentation\/the-sling-engine\/authentication\/authentication-authenticationhandler\/openid-authenticationhandler.html/g' | \
sed s'/{{ *refs\.authentication-authenticationhandler.path *}}/\/documentation\/the-sling-engine\/authentication\/authentication-authenticationhandler.html/g' | \
sed s'/{{ *refs\.authentication-framework.path *}}/\/documentation\/the-sling-engine\/authentication\/authentication-framework.html/g' | \
sed s'/{{ *refs\.authentication-tasks.path *}}/\/documentation\/the-sling-engine\/authentication\/authentication-tasks.html/g' | \
sed s'/{{ *refs\.authentication.path *}}/\/documentation\/the-sling-engine\/authentication.html/g' | \
sed s'/{{ *refs\.default-mapping-and-rendering.path *}}/\/documentation\/the-sling-engine\/default-mapping-and-rendering.html/g' | \
sed s'/{{ *refs\.dispatching-requests.path *}}/\/documentation\/the-sling-engine\/dispatching-requests.html/g' | \
sed s'/{{ *refs\.errorhandling.path *}}/\/documentation\/the-sling-engine\/errorhandling.html/g' | \
sed s'/{{ *refs\.featureflags.path *}}/\/documentation\/the-sling-engine\/featureflags.html/g' | \
sed s'/{{ *refs\.filters.path *}}/\/documentation\/the-sling-engine\/filters.html/g' | \
sed s'/{{ *refs\.mappings-for-resource-resolution.path *}}/\/documentation\/the-sling-engine\/mappings-for-resource-resolution.html/g' | \
sed s'/{{ *refs\.request-listeners.path *}}/\/documentation\/the-sling-engine\/request-listeners.html/g' | \
sed s'/{{ *refs\.request-parameters.path *}}/\/documentation\/the-sling-engine\/request-parameters.html/g' | \
sed s'/{{ *refs\.resources.path *}}/\/documentation\/the-sling-engine\/resources.html/g' | \
sed s'/{{ *refs\.service-authentication.path *}}/\/documentation\/the-sling-engine\/service-authentication.html/g' | \
sed s'/{{ *refs\.servlets.path *}}/\/documentation\/the-sling-engine\/servlets.html/g' | \
sed s'/{{ *refs\.sling-api-crud-support.path *}}/\/documentation\/the-sling-engine\/sling-api-crud-support.html/g' | \
sed s'/{{ *refs\.sling-properties.path *}}/\/documentation\/the-sling-engine\/sling-properties.html/g' | \
sed s'/{{ *refs\.the-sling-launchpad.path *}}/\/documentation\/the-sling-engine\/the-sling-launchpad.html/g' | \
sed s'/{{ *refs\.url-decomposition.path *}}/\/documentation\/the-sling-engine\/url-decomposition.html/g' | \
sed s'/{{ *refs\.url-to-script-resolution.path *}}/\/documentation\/the-sling-engine\/url-to-script-resolution.html/g' | \
sed s'/{{ *refs\.wrap-or-decorate-resources.path *}}/\/documentation\/the-sling-engine\/wrap-or-decorate-resources.html/g' | \
sed s'/{{ *refs\.the-sling-engine.path *}}/\/documentation\/the-sling-engine.html/g' | \
sed s'/{{ *refs\.46-line-blog.path *}}/\/documentation\/tutorials-how-tos\/46-line-blog.html/g' | \
sed s'/{{ *refs\.getting-resources-and-properties-in-sling.path *}}/\/documentation\/tutorials-how-tos\/getting-resources-and-properties-in-sling.html/g' | \
sed s'/{{ *refs\.how-to-manage-events-in-sling.path *}}/\/documentation\/tutorials-how-tos\/how-to-manage-events-in-sling.html/g' | \
sed s'/{{ *refs\.installing-and-upgrading-bundles.path *}}/\/documentation\/tutorials-how-tos\/installing-and-upgrading-bundles.html/g' | \
sed s'/{{ *refs\.jackrabbit-persistence.path *}}/\/documentation\/tutorials-how-tos\/jackrabbit-persistence.html/g' | \
sed s'/{{ *refs\.testing-sling-based-applications.path *}}/\/documentation\/tutorials-how-tos\/testing-sling-based-applications.html/g' | \
sed s'/{{ *refs\.tutorials-how-tos.path *}}/\/documentation\/tutorials-how-tos.html/g' | \
sed s'/{{ *refs\.documentation.path *}}/\/documentation.html/g' | \
sed s'/{{ *refs\.403.path *}}/\/errors\/403.html/g' | \
sed s'/{{ *refs\.404.path *}}/\/errors\/404.html/g' | \
sed s'/{{ *refs\.guides.path *}}/\/guides.html/g' | \
sed s'/{{ *refs\.index.path *}}/\/index.html/g' | \
sed s'/{{ *refs\.javadoc-io.path *}}/\/javadoc-io.html/g' | \
sed s'/{{ *refs\.links.path *}}/\/links.html/g' | \
sed s'/{{ *refs\.media.path *}}/\/media.html/g' | \
sed s'/{{ *refs\.sling-ide-tooling-11-released.path *}}/\/news\/sling-ide-tooling-11-released.html/g' | \
sed s'/{{ *refs\.sling-launchpad-8-released.path *}}/\/news\/sling-launchpad-8-released.html/g' | \
sed s'/{{ *refs\.sling-launchpad-9-released.path *}}/\/news\/sling-launchpad-9-released.html/g' | \
sed s'/{{ *refs\.news.path *}}/\/news.html/g' | \
sed s'/{{ *refs\.old-stuff.path *}}/\/old-stuff.html/g' | \
sed s'/{{ *refs\.plugins.path *}}/\/plugins.html/g' | \
sed s'/{{ *refs\.apache-sling-community-roles-and-processes.path *}}/\/project-information\/apache-sling-community-roles-and-processes.html/g' | \
sed s'/{{ *refs\.project-license.path *}}/\/project-information\/project-license.html/g' | \
sed s'/{{ *refs\.project-team.path *}}/\/project-information\/project-team.html/g' | \
sed s'/{{ *refs\.security.path *}}/\/project-information\/security.html/g' | \
sed s'/{{ *refs\.project-information.path *}}/\/project-information.html/g' | \
sed s'/{{ *refs\.site-conversion.path *}}/\/site-conversion.html/g' | \
cat
