meta(charset:"utf-8") newLine()
meta(name:"viewport", content:"width=device-width, initial-scale=1.0") newLine()
title("${config.blog_title}") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/asciidoctor.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/foundation.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/social_foundicons.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/prettify.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/desert.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/app.css") newLine()
newLine()
script(src:"${config.site_contextPath}js/vendor/modernizr.js"){} newLine()
script(src:"${config.site_contextPath}js/app.js"){} newLine()